export const data =  {
    services: [
        '',
        'Уборка квартиры', 
        'Уборка квартиры после ремонта',
        'Уборка коттеджа', 
        'Уборка коттеджа после ремонта',
        'Уборка офиса'],
    typeRoom: ['', 'Экспресс уборка', 'Генеральная уборка', 'VIP уборка'],
    typeFurniture: ['', 'С мебелью', 'Без мебели'],
    typeCottage: ['', 'Экспресс уборка', 'Генеральная уборка', 'VIP уборка'],
    typeCottageRepair: ['', 'Деревянный дом', 'Коттедж'],
    typeOffice: ['', 'Генеральная уборка', 'Уборка после ремонта без мебели', 'Уборка после ремонта c мебелью'],
    squareRoom: ['', 'до 50 м²', 'до 70 м²', 'до 90 м²', 'до 120 м²'],
    squareFurniture: ['', 'до 40 м²', 'до 50 м²', 'до 60 м²', 'до 70 м²', 'до 80 м²', 'до 90 м²', 'до 100 м²'],
    squareCottage: ['', 'до 100 м²', 'до 150 м²', 'до 200 м²', 'до 250 м²', 'до 300 м²', 'до 350 м²'],
}


export const cards = [
    {
        id: 1,
        url: './img/calculator_glasses.png',
        alt: 'Glasses',
        category: 'Услуга',
        title: 'Помыть посуду',
        price: '250 руб / 60 мин',
        buttons: true,
        value: 250,
        duration: 60,
        square: null,
        quantity: null
    },
    {
        id: 2,
        url: './img/calculator_multi.png',
        alt: 'Multi',
        category: 'Услуга',
        title: 'Помыть СВЧ печь',
        price: '250 руб',
        buttons: false,
        value: 250,
        duration: null,
        square: null,
        quantity: null
    },
    {
        id: 3,
        url: './img/calculator_friges.jpg',
        alt: 'Heat',
        category: 'Услуга',
        title: 'Помыть духовку',
        price: '450 руб',
        buttons: false,
        value: 450,
        duration: null,
        square: null,
        quantity: null
    },
    {
        id: 4,
        url: './img/calculator_friges2.jpg',
        alt: 'Glasses',
        category: 'Услуга',
        title: 'Помыть холодильник',
        price: '450 руб',
        buttons: false,
        value: 450,
        duration: null,
        square: null,
        quantity: null
    },
    {
        id: 5,
        url: './img/calculator_kitchen-shelves.jpg',
        alt: 'Kitchen',
        category: 'Услуга',
        title: 'Помыть кухонныe шкафы',
        price: '500 руб',
        buttons: false,
        value: 500,
        duration: null,
        square: null,
        quantity: null
    },
    {
        id: 6,
        url: './img/calculator_windows.jpg',
        alt: 'Windows',
        category: 'Услуга',
        title: 'Мойка окон',
        price: 'от 190 руб / окно',
        buttons: false,
        value: 190,
        duration: null,
        square: null,
        quantity: null
    },{
        id: 7,
        url: './img/calculator_lamp.jpg',
        alt: 'Lamp',
        category: 'Услуга',
        title: 'Помыть люстру',
        price: '350 руб / шт',
        buttons: true,
        value: 350,
        duration: null,
        square: null,
        quantity: 1
    },
    {
        id: 8,
        url: './img/calculator_balcon.png',
        alt: 'Balcon',
        category: 'Услуга',
        title: 'Помыть балкон',
        price: '300 руб',
        buttons: false,
        value: 300,
        duration: null,
        square: null,
        quantity: null
    },
    {
        id: 9,
        url: './img/calculator_ironing.jpg',
        alt: 'Ironing',
        category: 'Услуга',
        title: 'Глажка белья',
        price: '500 руб / 60 мин',
        buttons: true,
        value: 500,
        duration: 60,
        square: null,
        quantity: null
    },
    {
        id: 10,
        url: './img/calculator_vacuum.jpg',
        alt: 'Vacuum',
        title: 'Химчистка ковров',
        price: 'от 70 руб / м²',
        buttons: true,
        value: 70,
        square: 1,
        duration: null,
        quantity: null
    },
    {
        id: 11,
        url: './img/calculator_tul.jpg',
        alt: 'Tul',
        category: 'Услуга',
        title: 'Химчистка штор',
        price: 'от 250 руб / м²',
        buttons: true,
        value: 250,
        square: 1,
        duration: null,
        quantity: null
    },
    {
        id: 12,
        url: './img/calculator_textil.jpg',
        alt: 'Textil',
        category: 'Услуга',
        title: 'Химчистка текстильной мебели',
        price: 'от 250 руб / шт',
        buttons: true,
        value: 250,
        quantity: 1,
        duration: null,
        square: null,
    },
    {
        id: 13,
        url: './img/calculator_leather.jpg',
        alt: 'Leather',
        category: 'Услуга',
        title: 'Химчистка кожаной мебели',
        price: 'от 450 руб / шт',
        buttons: true,
        value: 450,
        square: null,
        quantity: 1,
        duration: null
    },
    {
        id: 14,
        url: './img/calculator_leather.jpg',
        alt: 'Matrass',
        title: 'Химчистка матрасов',
        price: 'от 1350 руб / шт',
        buttons: true,
        value: 450,
        square: null,
        quantity: null,
        duration: null
    }

]

export const textilCards = [
    {
        id: 1,
        url: '../img/price__sofa-2.png',
        alt: 'Sofa-2',
        category: 'Химчистка текстильной мебели',
        title: '2 посадочных места',
        price: '2100 руб',
        value: 2100,
    },
    {
        id: 2,
        url: '../img/price__sofa-3.png',
        alt: 'Sofa-3',
        category: 'Химчистка текстильной мебели',
        title: '3 посадочных места',
        price: '2700 руб',
        value: 2700,
    },
    {
        id: 3,
        url: '../img/price__sofa-corner-2.png',
        alt: 'Sofa-corner-2x',
        category: 'Химчистка текстильной мебели',
        title: 'Угловой диван',
        price: '3300 руб',
        value: 3300,
    },
    {
        id: 4,
        url: '../img/price__sofa-corner-3.png',
        alt: 'Sofa-corner-3x',
        category: 'Химчистка текстильной мебели',
        title: 'Большой угловой диван',
        price: '4500 руб',
        value: 4500,
    },
    {
        id: 5,
        url: '../img/price__pillow.png',
        alt: 'Pillow',
        category: 'Химчистка текстильной мебели',
        title: 'Декоративная подушка (40х40)',
        price: '150 руб',
        value: 150,
    },
    {
        id: 6,
        url: '../img/price__pillow-back.png',
        alt: 'Pillow-back',
        category: 'Химчистка текстильной мебели',
        title: 'Подушка спинки',
        price: '250 руб',
        value: 250,
    },
    {
        id: 7,
        url: '../img/price__armchair-1.png',
        alt: 'Armchair-1',
        category: 'Химчистка текстильной мебели',
        title: 'Кресло для отдыха',
        price: '1000 руб',
        value: 1000,
    },
    {
        id: 8,
        url: '../img/price__armchair-2.png',
        alt: 'Armchair-2',
        category: 'Химчистка текстильной мебели',
        title: 'Кресло со спальным механизмом',
        price: '1300 руб',
        value: 1300,
    },
    {
        id: 9,
        url: '../img/price__roller-pillow-1.png',
        alt: 'Roller-pillow-1',
        category: 'Химчистка текстильной мебели',
        title: 'Пуф 40х40',
        price: '400 руб',
        value: 400,
    },
    {
        id: 10,
        url: '../img/price__roller-pillow-2.png',
        alt: 'Roller-pillow-2',
        category: 'Химчистка текстильной мебели',
        title: 'Пуф 80х80',
        price: '800 руб',
        value: 800,
    },
    {
        id: 11,
        url: '../img/price__chair-1.png',
        alt: 'Chair-1',
        category: 'Химчистка текстильной мебели',
        title: 'Стул без мягкой спинки',
        price: '200 руб',
        value: 200,
    },
    {
        id: 12,
        url: '../img/price__chair-2.png',
        alt: 'Chair-2',
        category: 'Химчистка текстильной мебели',
        title: 'Стул с мягкой спинкой',
        price: '300 руб',
        value: 300,
    },
    {
        id: 13,
        url: '../img/price__chair-3.png',
        alt: 'Chair-3',
        category: 'Химчистка текстильной мебели',
        title: 'Офисное кресло',
        price: '350 руб',
        value: 350,
    },
    {
        id: 14,
        url: '../img/price__chair-4.png',
        alt: 'Chair-4',
        category: 'Химчистка текстильной мебели',
        title: 'Офисный стул',
        price: '150 руб',
        value: 150,
    },
    {
        id: 15,
        url: '../img/price__chair-5.png',
        alt: 'Chair-5',
        category: 'Химчистка текстильной мебели',
        title: 'Кресло "директора"',
        price: '650 руб',
        value: 650,
    },
]

export const leatherCards = [
    {
        id: 1,
        url: '../img/price__sofa-2.png',
        alt: 'Sofa-2',
        category: 'Химчистка кожаной мебели',
        title: '2 посадочных места',
        price: '2600 руб',
        value: 2600,
    },
    {
        id: 2,
        url: '../img/price__sofa-3.png',
        alt: 'Sofa-3',
        category: 'Химчистка кожаной мебели',
        title: '3 посадочных места',
        price: '3300 руб',
        value: 3300,
    },
    {
        id: 3,
        url: '../img/price__sofa-corner-2.png',
        alt: 'Sofa-corner-2x',
        category: 'Химчистка кожаной мебели',
        title: 'Угловой диван',
        price: '4100 руб',
        value: 4100,
    },
    {
        id: 4,
        url: '../img/price__sofa-corner-3.png',
        alt: 'Sofa-corner-3x',
        category: 'Химчистка кожаной мебели',
        title: 'Большой угловой диван',
        price: '5750 руб',
        value: 5750,
    },
    {
        id: 5,
        url: '../img/price__pillow.png',
        alt: 'Pillow',
        category: 'Химчистка кожаной мебели',
        title: 'Декоративная подушка (40х40)',
        price: '200 руб',
        value: 200,
    },
    {
        id: 6,
        url: '../img/price__pillow-back.png',
        alt: 'Pillow-back',
        category: 'Химчистка кожаной мебели',
        title: 'Подушка спинки',
        price: '350 руб',
        value: 350,
    },
    {
        id: 7,
        url: '../img/price__armchair-1.png',
        alt: 'Armchair-1',
        category: 'Химчистка кожаной мебели',
        title: 'Кресло для отдыха',
        price: '1500 руб',
        value: 1500,
    },
    {
        id: 8,
        url: '../img/price__armchair-2.png',
        alt: 'Armchair-2',
        category: 'Химчистка кожаной мебели',
        title: 'Кресло со спальным механизмом',
        price: '1800 руб',
        value: 1800,
    },
    {
        id: 9,
        url: '../img/price__roller-pillow-1.png',
        alt: 'Roller-pillow-1',
        category: 'Химчистка кожаной мебели',
        title: 'Пуф 40х40',
        price: '650 руб',
        value: 650,
    },
    {
        id: 10,
        url: '../img/price__roller-pillow-2.png',
        alt: 'Roller-pillow-2',
        category: 'Химчистка кожаной мебели',
        title: 'Пуф 80х80',
        price: '1200 руб',
        value: 1200,
    },
    {
        id: 11,
        url: '../img/price__chair-1.png',
        alt: 'Chair-1',
        category: 'Химчистка кожаной мебели',
        title: 'Стул без мягкой спинки',
        price: '300 руб',
        value: 300,
    },
    {
        id: 12,
        url: '../img/price__chair-2.png',
        alt: 'Chair-2',
        category: 'Химчистка кожаной мебели',
        title: 'Стул с мягкой спинкой',
        price: '450 руб',
        value: 450,
    },
    {
        id: 13,
        url: '../img/price__chair-3.png',
        alt: 'Chair-3',
        category: 'Химчистка кожаной мебели',
        title: 'Офисное кресло',
        price: '500 руб',
        value: 500,
    },
    {
        id: 14,
        url: '../img/price__chair-4.png',
        alt: 'Chair-4',
        category: 'Химчистка кожаной мебели',
        title: 'Офисный стул',
        price: '200 руб',
        value: 200,
    },
    {
        id: 15,
        url: '../img/price__chair-5.png',
        alt: 'Chair-5',
        category: 'Химчистка кожаной мебели',
        title: 'Кресло "директора"',
        price: '800 руб',
        value: 800,
    },
]

export const matrassCards = [
    {
        id: 1,
        url: '../img/price__mattress-1.png',
        alt: 'Mattress',
        category: 'Химчистка матрасов',
        title: 'Матрас 900х2000 (одна сторона)',
        price: '1350 руб',
        value: 1350,
    },
    {
        id: 2,
        url: '../img/price__mattress-1.png',
        alt: 'Mattress',
        category: 'Химчистка матрасов',
        title: 'Матрас 900х2000 (две стороны)',
        price: '1600 руб',
        value: 1600,
    }, 
    {
        id: 3,
        url: '../img/price__mattress-1.png',
        alt: 'Mattress',
        category: 'Химчистка матрасов',
        title: 'Матрас 1200х2000 (одна сторона)',
        price: '1800 руб',
        value: 1800,
    },
    {
        id: 4,
        url: '../img/price__mattress-1.png',
        alt: 'Mattress',
        category: 'Химчистка матрасов',
        title: 'Матрас 1200х2000 (две стороны)',
        price: '2200 руб',
        value: 2200,
    },
    {
        id: 5,
        url: '../img/price__mattress-2.png',
        alt: 'Mattress',
        category: 'Химчистка матрасов',
        title: 'Матрас 1400х2000 (одна сторона)',
        price: '2100 руб',
        value: 2100,
    },
    {
        id: 6,
        url: '../img/price__mattress-2.png',
        alt: 'Mattress',
        category: 'Химчистка матрасов',
        title: 'Матрас 1400х2000 (две стороны)',
        price: '2500 руб',
        value: 2500,
    }, 
    {
        id: 7,
        url: '../img/price__mattress-2.png',
        alt: 'Mattress',
        category: 'Химчистка матрасов',
        title: 'Матрас 1600х2000 (одна сторона)',
        price: '2400 руб',
        value: 2400,
    },
    {
        id: 8,
        url: '../img/price__mattress-2.png',
        alt: 'Mattress',
        category: 'Химчистка матрасов',
        title: 'Матрас 1600х2000 (две стороны)',
        price: '2800 руб',
        value: 2800,
    },
    {
        id: 9,
        url: '../img/price__mattress-3.png',
        alt: 'Mattress',
        category: 'Химчистка матрасов',
        title: 'Матрас 1800х2000 (одна сторона)',
        price: '2700 руб',
        value: 2700,
    },
    {
        id: 10,
        url: '../img/price__mattress-3.png',
        alt: 'Mattress',
        category: 'Химчистка матрасов',
        title: 'Матрас 1800х2000 (две стороны)',
        price: '3200 руб',
        value: 3200,
    },
]